name: CI
on:
  workflow_run:
    types:
      - completed
  push:
    branches: [ "main" ]
env:
    GITHUB_TOKEN: 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
    REPO_OWNER: alimelus
    REPO_NAME: github_delete

    
    
    
jobs:
  runid:
      runs-on: ubuntu-latest
      steps:
          - name: checkout repository
            uses: actions/checkout@v3

          - name: Delete Workflow Run
       
            run: |
                  # Get the workflow run ID from the event payload
                  RUN_ID=${{ github.event.workflow_run.id }}
        
                  # Make a DELETE request to the GitHub API to delete the workflow run
                  curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID"
                    
