name: delete
on:
  push:
    branches:
       hotfix

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete Workflow Runs
        id: delete-runs
        run: |
           # Get the list of workflow runs
            RUNS=$(curl -s -H "Authorization: token ${{ github.token }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs")
     

                    
