name: Delete Old Workflow Run

on:
 push:
   branches:
      hotfix

jobs:
  delete_old_run:
    runs-on: ubuntu-latest

    steps:
       - name: Set Date Environment Variable
         run: |
          # Calculate a week ago from today's date
          WEEK_AGO=$(date -u -d "7 days ago" +"%Y-%m-%dT%H:%M:%SZ")
          echo "WEEK_AGO=$WEEK_AGO" >> $GITHUB_ENV

       - name: Display Calculated Date
         run: |
          echo "One week ago: $WEEK_AGO"
