name: CI
on:
  push:
    branches:
       hotfix

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete Workflow Runs
        id: delete-runs
        run: |
           curl -X DELETE -H "Authorization: token ${{ github.token }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs/5936949807"
        

     

                    
