name: CI
on:
  push:
    branches: [ "main" ]
env:
    GITHUB_TOKEN: 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
    REPO_OWNER: alimelus
    REPO_NAME: github_delete
    
jobs:
  delete_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete Workflow Runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch a list of workflow runs
          RUNS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/actions/runs")

          # Loop through the runs and delete them
          for RUN in $(echo "$RUNS" | jq -r '.workflow_runs[] | @base64'); do
            RUN_JSON=$(echo "$RUN" | base64 -d)
            RUN_ID=$(echo "$RUN_JSON" | jq -r '.id')
            echo "Deleting workflow run $RUN_ID"
            curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID"
            sleep 1  # Sleep to avoid hitting API rate limits
          done

                    
