name: Delete Old Workflow Run

on:
 push:
   branches:
      hotfix

jobs:
  delete_old_run:
    runs-on: ubuntu-latest

    steps:
       - name: Set Date Environment Variable
         run: |
          # display current date
          date
          # Calculate day ago from today's date
          DAY_AGO=$(date -u -d "1 day ago" +"%Y-%m-%dT%H:%M:%SZ")
          echo "DAY_AGO=$DAY_AGO" >> $GITHUB_ENV

       - name: Display Calculated Date
         run: |
          echo "One day ago: $DAY_AGO"

          

       - name: Get Workflow Runs
         id: get_runs
         run: |
            # Get the list of completed workflow runs and sort them by creation date
              workflow_runs=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/workflows/github_delete/runs?status=completed" | jq '.workflow_runs | sort_by(.created_at) | reverse')
   
            # Get the ID of the previous workflow run (the second one in the sorted list)
            previous_run_id=$(echo "$workflow_runs" | jq -r '.[1].id')
            
            echo "Previous workflow run ID: $previous_run_id"
             API_URL="https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100"
             RUNS=$(curl -s "$API_URL")
             DAY_AGO_RUNS=$(echo "$RUNS" | jq --arg DAY_AGO "$DAY_AGO" '.workflow_runs[] | select(.created_at > $DAY_AGO) | .id')
             echo "One week ago: $DAY_AGO_RUNS"
              curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                   "https://api.github.com/repos/${{ github.repository }}/actions/runs/$DAY_AGO_RUNS"
                   echo "Deleted workflow run $DAY_AGO_RUNS"
               fi
              done


         
  
 
