name: Delete Old Workflow Run

on:
 push:
   branches:
      hotfix

jobs:
  delete_old_run:
     runs-on: ubuntu-latest
     steps:
       - name: Set Date Environment Variable
         run: |
            # display current date
            date
            # Calculate day ago from today's date
            DATE_TWO_WEEKS_AGO=$(date -u -d "2 weeks ago" +"%Y-%m-%dT%H:%M:%SZ")
            echo "DATE_TWO_WEEKS_AGO=$DATE_TWO_WEEKS_AGO" >> $GITHUB_ENV

            workflow_run_ids=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs" | jq --arg date "$DATE_TWO_WEEKS_AGO" -r '.workflow_runs[] | select(.created_at < $date) | .id')
            echo workflow_run_ids: $workflow_run_ids

            for workflow_run_id in $workflow_run_ids; do
            curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs/$workflow_run_id"
            echo "Deleted workflow run: $workflow_run_id"
            done
             
                        




      
  
 
