name: Delete Old Workflow Run

on:
 push:
   branches:
      hotfix

jobs:
  delete_old_run:
    runs-on: ubuntu-latest

    steps:
       - name: Set Date Environment Variable
         run: |
          # display current date
          date
          # Calculate day ago from today's date
          DAY_AGO=$(date -u -d "1 day ago" +"%Y-%m-%dT%H:%M:%SZ")
          echo "DAY_AGO=$DAY_AGO" >> $GITHUB_ENV

       - name: Display Calculated Date
         run: |
          echo "One day ago: $DAY_AGO"

       - name: Get Workflow Runs
         id: get_runs
         run: |
           API_URL="https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100"
           RUNS=$(curl -s "$API_URL")
           DAY_AGO_RUNS=$(echo "$RUNS" | jq --arg DAY_AGO "$DAY_AGO" '.workflow_runs[] | select(.created_at > $DAY_AGO) | .id')
           echo "One week ago: $DAY_AGO_RUNS"

       - name: Delete Workflow Runs  
         run: |
            curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                 "https://api.github.com/repos/${{ github.repository }}/actions/runs/$DAY_AGO_RUNS"
            echo "Deleted workflow run: $DAY_AGO_RUNS"
          
