name: Delete Old Workflow Run

on:
 push:
   branches:
      hotfix

jobs:
  delete_old_run:
    runs-on: ubuntu-latest

    steps:
       - name: Set Date Environment Variable
         run: |
           # Initialize an empty array to store workflow run IDs
             workflow_run_ids=()
             
             # Initial page number
             page=1

            # display current date
            date
            # Calculate day ago from today's date
            DAY_AGO=$(date -u -d "1 day ago" +"%Y-%m-%dT%H:%M:%SZ")
            echo "DAY_AGO=$DAY_AGO" >> $GITHUB_ENV


            while true; do
             # Fetch workflow run IDs for the current page
             response=$(curl -s -H "Authorization: Bearer $ACCESS_TOKEN" "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100&page=$page")
           
             # Extract and append workflow run IDs to the array
             ids=$(echo "$response" | jq -r ".workflow_runs[].id")
             if [ -z "$ids" ]; then
               break
             fi
             workflow_run_ids+=($ids)
           
             # Move to the next page
             page=$((page + 1))
           done
           
           # Count the total number of fetched workflow run IDs
           total_ids=${#workflow_run_ids[@]}
           
           # Print the workflow run IDs and the total count
           for workflow_run_id in "${workflow_run_ids[@]}"; do
             echo "Workflow run ID: $workflow_run_id"
           done
           
           echo "Total Workflow Run IDs: $total_ids"





      
  
 
