name: CI
on:
  push:
    branches: [ "main" ]
env:
    
    GITHUB_TOKEN: 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
    
jobs:
  runid:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Fetch Workflow Runs
        id: fetch-runs
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          RUNS=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/${{ github.repository }}/actions/runs")
          echo "::set-output name=runs::$RUNS"

      - name: Delete Previous Run
        if: ${{ steps.extract-previous-id.outputs.previous-id != null }}
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          PREVIOUS_ID="${{ steps.extract-previous-id.outputs.previous-id }}"
          curl -X DELETE -H "Authorization: token $TOKEN" "https://api.github.com/repos/${{ github.repository }}/actions/runs/$PREVIOUS_ID"

          
