name: CI
on:
  push:
    branches: [ "main" ]
    
env:
    GH_TOKEN: ${{ github.token }}

jobs:
  runid:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Display current Workflow Run ID
        run: |
            echo "Workflow Run ID: ${{ github.run_id }}"

      - name: get a list of workflow runs 
        run: |
             echo "getting list of workflow runs.."
             gh api \
             /repos/alimelus/github_delete/actions/runs

          
