name: CI
on:
  push:
    branches: [ "main" ]
env:
    GITHUB_TOKEN: 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
    OWNER: alimelus
    REPO: github_delete
    RUN_ID: 5889009749

   
   
jobs:
  delete_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete Workflow Runs
        run: |
              curl -s \
                    -X DELETE \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer $GITHUB_TOKEN"\
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/$OWNER/$REPO/actions/runs/$1
                    echo "Successfully deleted a workflow's run with $1"
         

                    
