name: Delete Old Workflow Runs

on:
  workflow_dispatch:
    inputs:
      days_ago:
        description: 'Number of days ago to consider runs as old'
        required: true

jobs:
  delete_runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete Old Runs
        run: |
          DAYS_AGO=${{ github.event.inputs.days_ago }}
          
          # Calculate the date threshold
          THRESHOLD_DATE=$(date -u -d "$DAYS_AGO days ago" +%Y-%m-%dT%H:%M:%SZ)
          
          # Use the GitHub API to fetch a list of workflow runs
          # Replace this with your actual API call
          # Ensure to filter by the calculated threshold date
          RUNS_JSON=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100&status=completed&event=push")

          # Loop through and delete old workflow run IDs
          for run_id in $(echo "$RUNS_JSON" | jq -r ".workflow_runs[] | select(.created_at < \"$THRESHOLD_DATE\") | .id"); do
              echo "Deleting workflow run ID: $run_id"
              curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
          done
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
