name: CI
on:
  push:
    branches: [ "main" ]
env:
    GH_TOKEN: ${{ github.token }}
    GITHUB_TOKEN: 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
    
jobs:
  runid:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Display current Workflow Run ID
        run: |
            echo " current Workflow Run ID: ${{ github.run_id }}"

      - name: get a list of workflow runs 
        run: |
             #echo "getting list of workflow runs.."
             #gh api \
             #/repos/alimelus/github_delete/actions/runs

             curl -X DELETE \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/alimelus/github_delete/actions/runs/5878032657/cancel"

          
