name: Delete Old Workflow Run

on:
 push:
   branches:
      hotfix

jobs:
  delete_old_run:
    runs-on: ubuntu-latest

    steps:
      - name: Calculate Date Range
        run: |
             
             # Calculate the date 1 week ago
             THRESHOLD=$(date -u -d "7 days ago" +"%Y-%m-%dT%H:%M:%SZ")
             echo "THRESHOLD=$THRESHOLD" >> $GITHUB_ENV
