name: Delete Old Workflow Runs

on:
  workflow_dispatch:
    inputs:
      days_ago:
        description: 'Number of days ago to consider runs as old'
        required: true

jobs:
  delete_runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete Old Runs
        run: |
          DAYS_AGO=${{ github.event.inputs.days_ago }}
          
          # Calculate the date threshold
          THRESHOLD_DATE=$(date -u -d "$DAYS_AGO days ago" +%Y-%m-%dT%H:%M:%SZ)
          
          # Use your tool or API to fetch old run IDs based on the calculated threshold date
          # Replace this with your actual API call
          OLD_RUN_IDS=$(curl -s -H "Authorization: Bearer ${{ secrets.AUTH_TOKEN }}" "https://api.github.com/workflow_runs?created_before=$THRESHOLD_DATE" | jq -r)

          # Loop through and delete old run IDs
          for run_id in $OLD_RUN_IDS; do
              echo "Deleting workflow run ID: $run_id"
              curl -X DELETE -H "Authorization: Bearer ${{ secrets.AUTH_TOKEN }}" "https://api.github.com/workflow_runs/$run_id"
          done

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
