name: Delete Old Workflow Run

on:
 push:
   branches:
      hotfix

jobs:
  delete_old_run:
    runs-on: ubuntu-latest

    steps:
      - name: Calculate Date Range
        run: |
             date
             # Calculate the date 1 week ago
             threshold_date=$(date -d "1 week ago" +"%Y-%m-%d")
             echo "THRESHOLD=$THRESHOLD" >> $GITHUB_ENV
