name: CI
on:
  push:
    branches: [ "main" ]
    
env:
    GH_TOKEN: ${{ github.token }}

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
             echo  ${{ github.run_id }} 

      # Runs a set of commands using the runners shell
      - name: Run a script
        run: |
          # list workflows
            gh api \
           /repos/alimelus/github_delete/actions/runs

          
