name: Delete One Day Old Workflow Runs

on:
  push:
    branches:
       test
jobs:
  delete-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Delete One Day Old Workflow Runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ONE_DAY_AGO=$(date -u -d '1 day ago' +"%Y-%m-%dT%H:%M:%SZ")
          API_URL="https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100"

          # Fetch workflow runs and delete runs older than one day ago
          runs=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "$API_URL")
          for run in $(echo "$runs" | jq -c '.workflow_runs[] | select(.created_at < "'"$ONE_DAY_AGO"'")'); do
            run_id=$(echo "$run" | jq -r '.id')
            echo "Deleting run ID $run_id"
            curl -s -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
          done
