name: Delete One Day Old Workflow Runs

on:
  push:
   branches:
     test
jobs:
  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Get Workflow Runs
        id: get_runs
        run: |
          API_URL="https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100"
          RUNS=$(curl -s "$API_URL")
          # Filter and delete runs older than one day ago
          while IFS= read -r line; do
            created_at=$(echo "$line" | jq -r '.created_at')
            run_id=$(echo "$line" | jq -r '.id')
            
            if [[ "$created_at" < "$(date -u -d `1 day ago` +%Y-%m-%dT%H:%M:%SZ')" ]]; then
              echo "Deleting run ID $run_id"
              curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                   "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
            fi
            done <<< "$RUNS"
