name: Housekeeping
on:
  push:
    branches:
      test
jobs:
  delete_old_runs:
    runs-on: ubuntu-latest

    steps:
      - name: Calculate Date Threshold
        run: |
          # Calculate a week ago from today's date
          WEEK_AGO=$(date -u -d "7 days ago" +"%Y-%m-%dT%H:%M:%SZ")
          echo "WEEK_AGO=$WEEK_AGO" >> $GITHUB_ENV

      - name: Get Workflow Runs
        id: get_runs
        run: |
          API_URL="https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100"
          RUNS=$(curl -s "$API_URL")

          # Filter runs older than a week ago and format as newline-separated list
          WEEK_AGO_RUNS=$(echo "$RUNS" | jq -r --arg WEEK_AGO "$WEEK_AGO" '.workflow_runs[] | select(.created_at < $WEEK_AGO) | .id' | tr '\n' ' ')

          # Pass the list of run IDs as an environment variable
          echo "WEEK_AGO_RUNS=$WEEK_AGO_RUNS" >> $GITHUB_ENV

      - name: Delete Workflow Runs
        run: |
          # Loop through and delete each identified run using curl
          for run_id in $WEEK_AGO_RUNS; do
            curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                 "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
            echo "Deleted workflow run: $run_id"
          done
