name: Delete Old Workflow Run
on:
 push:
   branches:
      test
jobs:
  delete_old_run:
    runs-on: ubuntu-latest
    steps:
       - name: Get Workflow Runs
         id: get_runs
         run: |
             # Fetch workflow run IDs using jq and curl
               workflow_run_ids=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs" | jq -r ".workflow_runs[].id")
               
              
