
name: Delete Multiple Workflow Runs

on:
  workflow_dispatch:
    inputs:
      run-ids:
        description: 'Workflow Run IDs to delete (comma-separated)'
        required: true

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Workflow Runs
        run: |
          IFS=',' read -ra run_ids <<< "${{ github.event.inputs.run-ids }}"
          for run_id in "${run_ids[@]}"; do
            echo "Deleting workflow run with ID: $run_id"
            curl -X DELETE \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
          done
