name: Delete Sub Workflow Runs

on:
  workflow_dispatch:
    inputs:
      parent-run-id:
        description: 'Parent Workflow Run ID'
        required: true
      sub-run-ids:
        description: 'Comma-separated list of Sub Workflow Run IDs to delete'
        required: true

jobs:
  delete-sub-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Delete Sub Workflow Runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PARENT_RUN_ID: ${{ github.event.inputs.parent-run-id }}
          SUB_RUN_IDS: ${{ github.event.inputs.sub-run-ids }}
        run: |
          IFS=',' read -ra sub_run_ids <<< "$SUB_RUN_IDS"
          
          for sub_run_id in "${sub_run_ids[@]}"; do
            echo "Deleting sub workflow run with ID: $sub_run_id"
            curl -X DELETE \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$sub_run_id"
          done
