name: Delete Sub Workflow Runs

on:
 push:
   branches:
     main

jobs:
  delete-sub-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Delete Sub Workflow Runs
        run: |
          gh api repos/alimelus/github_delete/actions/workflows/6087040686/runs
           env:
             GH_TOKEN: ${{ GITHUB_TOKEN }}
