name: Delete Workflow Runs for a Single Action
on:
  push:
    branches:
       - main
jobs:
  delete-action-runs:
    runs-on: ubuntu-latest
    steps:
        OWNER="alimelus"
        REPO="github_delete"
  
        WORKFLOW_FILE=".github/workflows/newfile.yml"
        ACTION_NAME="Delete workflow runs" 
         workflow_id=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/workflows" | jq -r '.workflows[] | select(.path == "'"$WORKFLOW_FILE"'") | .id')
        
        if [ -n "$workflow_id" ]; then
          # Get all runs for the workflow
          run_ids=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$workflow_id/runs" | jq -r '.workflow_runs[] | select(.name == "'"$ACTION_NAME"'") | .id')
        
          for run_id in $run_ids; do
            echo "Deleting run ID $run_id"
            curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -X DELETE "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
          done
        else
          echo "Workflow not found."
        fi
