name: Delete Workflow Runs for a Single Action
on:
  push:
    branches:
       main
jobs:
  delete-action-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Delete Action Runs
        run: |
          # Get workflow IDs with status "success"
          workflow_ids=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/workflows" | jq '.workflows[] | select(.state == "success") | .id')
          
          for workflow_id in $workflow_ids
          do
            echo "Listing runs for the workflow ID $workflow_id"
            run_ids=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$workflow_id/runs" | jq '.workflow_runs[].id')
          
            for run_id in $run_ids
            do
              echo "Deleting Run ID $run_id"
              curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -X DELETE "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
            done
          done
          
