name: Displaying current and previous workflow run id

on:
  push:
    branches:
       feature

jobs:
  dispalying_run_id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      
      - name: Display current & Previous Workflow Run ID
        run: |
            echo " current Workflow Run ID: ${{ github.run_id }}"
            # applying deletion on workflow run id
            gh auth login
            gh workflow run delete 5889374095


         


    
