name: Displaying current and previous workflow run id

on:
  push:
    branches:
       feature
env:
  GITHUB_TOKEN: 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
jobs:
  dispalying_run_id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      
      - name: Display current & Previous Workflow Run ID
        run: |
            echo " current Workflow Run ID: ${{ github.run_id }}"
            # extract-previous-id
  
            # Use GitHub API to get the list of workflow runs
            response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs")
            # Parse JSON response and get the ID of the previous run
            previous_run_id=$(echo "$response" | jq -r '.workflow_runs[10].id')
            echo "Previous Run ID: $previous_run_id"
            # applying deletion on workflow run id
            curl -X DELETE \
            https://api.github.com/repos/alimelus/github_delete/actions/runs/5889374095

         


    
