name: Displaying current and previous workflow run id

on:
  push:
    branches:
       feature
env:
  GITHUB_TOKEN: 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
jobs:
  dispalying_run_id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Workflow Runs
        id: fetch-runs
        run: |
          TOKEN="${{ env.GITHUB_TOKEN }}"
          RUNS=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/${{ github.repository }}/actions/runs")
          

      - name: Extract Previous Run ID
        id: extract-previous-id
        run: |
          # Use GitHub API to get the list of workflow runs
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs")
          # Parse JSON response and get the ID of the previous run
          previous_run_id=$(echo "$response" | jq -r '.workflow_runs[1].id')
          echo "Previous Run ID: $previous_run_id"
         


      - name: Delete Previous Run
        if: ${{ steps.extract-previous-id.outputs.previous-id != null }}
        run: |
          TOKEN="${{ env.GITHUB_TOKEN }}"
          PREVIOUS_ID="${{ steps.extract-previous-id.outputs.previous-id }}"
          curl -X DELETE -H "Authorization: token $TOKEN" "https://api.github.com/repos/${{ github.repository }}/actions/runs/$PREVIOUS_ID"
