name: Delete Minutes Ago Workflow Runs

on:
  workflow_dispatch:
    inputs:
      minutes_ago:
        description: 'Number of minutes ago'
        required: true

jobs:
  delete_old_runs:
    runs-on: ubuntu-latest

    steps:
      - name: Calculate Date Threshold
        run: |
          # Calculate the time threshold (minutes ago)
          MINUTES_AGO=$((${{ github.event.inputs.minutes_ago }} * 60)) # Convert to seconds
          THRESHOLD=$(date -u -d "@$(( $(date +%s) - $MINUTES_AGO ))" +"%Y-%m-%dT%H:%M:%SZ")
          echo "THRESHOLD=$THRESHOLD" >> $GITHUB_ENV

      - name: Get Workflow Runs
        id: get_runs
        run: |
          API_URL="https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100"
          RUNS=$(curl -s "$API_URL")

          # Filter runs older than the specified time threshold
          OLDER_RUNS=$(echo "$RUNS" | jq --arg THRESHOLD "$THRESHOLD" '.workflow_runs[] | select(.created_at < $THRESHOLD) | .id')

          # Pass the list of run IDs as an environment variable
          echo "OLDER_RUNS=$OLDER_RUNS" >> $GITHUB_ENV

      - name: Display OLDER_RUNS
        run: |
          # Display the value of OLDER_RUNS in the workflow log
          echo "OLDER_RUNS: $OLDER_RUNS"
