name: Delete Workflow Run by passing runid as a parameter
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Workflow Run ID to Delete'
        required: true

jobs:
  delete_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Delete Workflow Run
        run: |
          # Set the base URL of your workflow management system's API
          API_BASE_URL="https://api.github.com/repos/${{ github.repository }}/actions/runs"

          # Get the run ID from the workflow_dispatch input
          RUN_ID="${{ github.event.inputs.run_id }}"

          # Construct the URL for deleting the workflow run
          DELETE_URL="$API_BASE_URL/$RUN_ID"

          # Send an HTTP DELETE request to delete the run
          curl -X DELETE $DELETE_URL
         
