name: Trigger Deletion Workflow

on:
  workflow_dispatch: 
    inputs:
      days-ago:
        description: 'Number of days ago for deletion'
        required: true
        
jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate Date
        id: cal-date
        run: |
          DATE_ONE_WEEK_AGO=$(date -u -d '-${{ github.event.inputs.days-ago }} days' +"%Y-%m-%dT%H:%M:%SZ")
          echo DATE_ONE_WEEK_AGO: $DATE_ONE_WEEK_AGO
          echo "::set-output name=date::$DATE_ONE_WEEK_AGO"
          
      - name: Fetch Workflow Run IDs
        id: fetch-ids
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs")
          echo "::set-output name=workflow-run-ids::$(echo "$response" | jq --arg date "${{ steps.cal-date.outputs.date }}" -r '.workflow_runs | map(select(.created_at < $date)) | .[].id')"

      - name: Print Workflow Run IDs
        run: |
          workflow_run_ids=${{ steps.fetch-ids.outputs.workflow-run-ids }}
          echo "Workflow Run IDs: $workflow_run_ids"

     
