name: Delete Minutes Ago Workflow Runs

on:
  workflow_dispatch:
    inputs:
      minutes_ago:
        description: 'Number of minutes ago'
        required: true

jobs:
  delete_old_runs:
    runs-on: ubuntu-latest

    steps:
      - name: Calculate Date Threshold
        run: |
          # Calculate the time threshold (minutes ago)
          MINUTES_AGO=$((${{ github.event.inputs.minutes_ago }} * 60)) # Convert to seconds
          THRESHOLD=$(date -u -d "@$(( $(date +%s) - $MINUTES_AGO ))" +"%Y-%m-%dT%H:%M:%SZ")
          echo "THRESHOLD=$THRESHOLD" >> $GITHUB_ENV

      - name: Get Workflow Runs
        id: get_runs
        run: |
          API_URL="https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100"
          RUNS=$(curl -s "$API_URL")

          # Filter runs older than the specified time threshold
          OLDER_RUNS=$(echo "$RUNS" | jq --arg THRESHOLD "$THRESHOLD" '.workflow_runs[] | select(.created_at <= $THRESHOLD) | .id')

      - name: Display OLDER_RUNS
        run: |
              # Loop through and display each identified run using echo
              for run_id in $OLDER_RUNS; do
                echo "Processing run: $run_id"
                echo "Command: echo 'OLDER_RUN: $run_id'"
                echo "----"
                echo "OLDER_RUN: $run_id"
              done
