name: Delete Specific Workflow Run

on:
  workflow_dispatch:
    inputs:
      run-id:
        description: 'Workflow Run ID to delete'
        required: true

jobs:
  delete-workflow-run:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Workflow Run
        run: |
          run_id=${{ github.event.inputs.run-id }}
          echo "Deleting workflow run with ID: $run_id"
          response=$(curl -X DELETE \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id")
          echo "Deletion Response: $response"
